CREATE TABLE IF NOT EXISTS hits (
    id          BIGINT generated by default as identity primary key,
    app         VARCHAR(50) not null,
    uri         VARCHAR(200) not null,
    ip          VARCHAR(15) not null,
    timestamp   TIMESTAMP WITHOUT TIME ZONE not null
    );