version: '3.1'
services:
  stats-service:
    build: ewm-stats-service/stat-server
    image: ewm-stat
    container_name: ewm_stats_server
    ports:
      - "9090:9090"
      - "5004:8888"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888

  stats-db:
    image: postgres:14.6-alpine
    command: ["postgres", "-c", "log_statement=all"]
    container_name: ewm_stats_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
