version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stat-server
    image: ewm-stat
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewm-stats-db

  ewm-stats-db:
    image: postgres:14.6-alpine
    container_name: ewm_stats_db
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-main-service
    image: ewm-main
    container_name: ewm_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/ewm-main-db
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-main-db:
    image: postgres:14.6-alpine
    container_name: ewm_main_db
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres